### ISSUE TITLE
Character from outer space ":00 by author" 

### ISSUE THREAD

**Issue by anat** [quantumsheep/vscode-esgiheader#4]
Here is the small mistake :

![image](https://user-images.githubusercontent.com/652592/67490518-a582de80-f673-11e9-9524-7a9b6d3d5bb1.png)

On windows

**Comment by quantumsheep** [comment]
Seems like the regex is wrong, can you produce it on UNIX-like systems? It may be the `\r` character not matching.

**Comment by quantumsheep** [comment]
`\n` is not counted as a character by `String.prototype.length` 🙃

**Comment by quantumsheep** [comment]
Just updated the extension from the VS Marketplace. You should see the update quite soon.
